### ISSUE TITLE
Highlights Js, System Message & Generating Table

### ISSUE THREAD

**Issue by shawnrockstarmckenzie84** [unconv/chat-wtf#6]
Master Shifu - Thanks for the great video!! Appreciate it very much. Anyway I will stick to your earlier version that you thought earlier since it works fine for me.

I have 3 queries though, see if you can help me out.

#1: highlights.js

You have use 'highlights' rel link in your code which is very useful for code markdown. But upon inspect on the console, this warning came out:

highlight.min.js:263 One of your code blocks includes unescaped HTML. This is a potentially serious security risk.
y	@	highlight.min.js:263
N	@	highlight.min.js:274
add_message	@	script.js:65
(anonymous)	@	script.js:11
highlight.min.js:264 https://github.com/highlightjs/highlight.js/wiki/security
y	@	highlight.min.js:264
N	@	highlight.min.js:274
add_message	@	script.js:65
(anonymous)	@	script.js:11
highlight.min.js:265 The element with unescaped HTML:
y	@	highlight.min.js:265
N	@	highlight.min.js:274
add_message	@	script.js:65
(anonymous)	@	script.js:11
highlight.min.js:266 
y	@	highlight.min.js:266
N	@	highlight.min.js:274
add_message	@	script.js:65
(anonymous)	@	script.js:11

Is this something to be concern about? or should we just ignore it?

To replicate this issues, I just ask it chatwtf to generate simple login php code. After it generate code, i simply reply thank you. After reply, only then the console generate this message.

#2: System_Message =>
I want to use the "system_message" for my chatwtf...the problem with this is that, when you fill text into teh system_message... upon refresh you browser...the system_message will come out at the top as part you chat conversation...if you refresh 5 times, it also will appear 5 times. How can we fill in the input for system_message, but when the user refresh the browser....it will not show the system message as part of the chat conversation.

#3: Generating Table
Is there any way generate table with perfect line like chatGPT? something like you did markdown to the code.
For example when you prompt ChatGPT to "generate table of fruits" it will genereate perfect line of table.
But for ChatWTF, it still generate the table of fruits, just that the line is 'Cut' & 'dotted'.

Thanks in advance Master Shifu, appreciate very much what you have done!

**Comment by unconv** [comment]
Thanks for posting the issue!

**1) Highlight.js warning**
This was because I used `hljs.highlightAll();` every time a message was added or updated. This tried to highlight every previous, already highlighted message as well, and caused the warning.

I switched it to this instead:
```javascript
message_item.querySelectorAll('pre code').forEach( (el) => {
    hljs.highlightElement(el);
} );
```

**2) Repeating system message**
I was indeed adding the system message to the beginning of the chat history every time, even when it was already saved to the context. I modified the code so that it skips the system message when reading the context, so that only the current system message from the settings is set. Also I skipped the system message from the loop that prints the chat messages on the frontend.

```php
if( $msg["role"] === "system" ) {
    continue;
}
```

**3) Tables in the response**
The Showdown markdown converter supports table styling as well, but it has to be enabled separately:

```javascript
const markdown_converter = new showdown.Converter({
    tables: true
});
```

I have fixed these issues and will update them tomorrow or the next day as I will post a new video creating the conversation history functionality.
