### ISSUE TITLE
maximum context length is 4097 tokens

### ISSUE THREAD

**Issue by shawnrockstarmckenzie84** [unconv/chat-wtf#7]
_"This model's maximum context length is 4097 tokens. However, you requested 4288 tokens (2288 in the messages, 2000 in the completion). Please reduce the length of the messages or completion. (context_length_exceeded)"_

Hi Master Shifu,
Appearantly, I encountered this message couples of times. Eventhough my messages were in short sentences. It's seems to me it combined all my previous prompt and completion as well. In your previous version of chatWTF...it did not combine the prompt, that's mean the tokens refresh to zero after each completions. But I notice this newer version, after a while probably 15 to 20 chat conversation, it return this message.

Occassionally, received this message to in console "Error 414 URI Too Long response " as well.

The latest version of ChatWTF is good and I like it coz it can stored historical chat data in SESSION (subject we did not clear the cache). However, if there anyway we can maintain the latest ChatWTF features but at the sametime include the rollback of where the tokens are refresh for new each prompt like what you did in previous version ChatWTF version?

Thanks in advance Shifu.

**Comment by unconv** [comment]
Hi! In order for the chatbot to remember the context of the chat (i.e. the previous messages), all previous messages need to be sent to the ChatGPT API, and they count as tokens for the prompt. There is a limit of 4097 tokens in the `gpt-3.5-turbo` model.

This could be fixed by 1) setting a token limit for the ChatGPT response or 2) implementing a "context window" so that old messages would automatically be dropped from the prompt when the conversation becomes too long. I didn't set a token limit in the streaming version of the chatbot, so it defaults to 2000. I should add this to the settings, so that it can be changed from there.

You can change the token limit by adding `"max_tokens" => 1000,` (or what ever number you want) to the `CURLOPT_POSTFIELDS` in `chatgpt.php`. If you don't need super long answers, you can probably set the limit even to 100-500. Now, because the token limit is 2000, the API refuses to respond even if the response would be 20 tokens, because it "allocates" 2000 tokens for the response, and if the prompt + 2000 tokens is more than 4097, it refuses to respond.

The `URI Too Long` error happens because currently the messages are sent as `GET` requests, so they are included in the URL and there is a limit to the size of the URL (depending on the server and the browser). I'm going to update it to use the `POST` method in the future.

**Comment by shawnrockstarmckenzie84** [comment]
Alight Shifu, thanks!
I'll do that for now while waiting for your latest video using POST method.

**Comment by shawnrockstarmckenzie84** [comment]
_This model's maximum context length is 4097 tokens. However, you requested 4277 tokens (3777 in the messages, 500 in the completion). Please reduce the length of the messages or completion. (context_length_exceeded)_

Master Shifu,
I have change the max-tokens to 500 as shown about. All my prompt are very short but still it said i have 3777 in messages. I guest taken into account the previous reponses by ChatWTF as well.

For the second option, I don't know how to implement the "context window"

**Comment by shawnrockstarmckenzie84** [comment]
Anyway, I shall wait for your POST method video. Probably that will fix it.
